language: node_js
node_js:
  - "6"
  - "4.4"
before_script:
  - npm install -g gulp
script: gulp
addons:
    code_climate:
        repo_token: c094dbd42ccfe3314beedad407785c872bb95037e2de191d829f35b878e5eb48
